### ISSUE TITLE
✨Feat: 재고 관리 기능 구현 

### ISSUE THREAD

**Issue by shinheekim** [Tasty-Inventory/Tasty-Inventory_BE#6]
## ✨ About Issue ✨
메뉴 및 재고(재료)의 CRUD 기능 구현
<br>

## ✅ Todo 
- [ ] 재고 예측 로직 구현
- [ ]  오늘의 발주량과 재고(현재고, 금일 발주량 필드 수정, 조회)
- [ ] 금일 판매량(수정, 조회)
- [ ] 메뉴 CRUD
- [ ] 재고 CRUD
