### ISSUE TITLE
🎉 Chore: 배포 관련

### ISSUE THREAD

**Issue by djdongjae** [Tasty-Inventory/Tasty-Inventory_BE#7]
## ✨ About Issue ✨
서버 임대, CI/CD 파이프라인 구축, 무중단 블루/그린 배포
* Server - AWS EC2: Amazon Linux 2023 AMI
* Database - AWS RDS: Mariadb 11
* Web Server - Nginx
* CI/CD - Github Actions, AWS S3,  AWS CodeDeploy
## ✅ Todo 

- [x] AWS EC2 및 RDS 배포
- [x] GitHub Actions, AWS S3, AWS CodeDeploy를 활용한 CI/CD 파이프라인 구축
- [x] Nginx 설정 및 Shell Script를 활용한 무중단 배포 환경 구축
